// packs.js — named prompt pools for the write card's daily deck (see deck.js).
// `everyday` reuses the existing PROMPTS verbatim; the others are content.
import { PROMPTS } from './prompts';

export const PROMPT_PACKS = [
  {
    id: 'everyday',
    name: 'Everyday',
    blurb: 'Open questions for an ordinary day.',
    prompts: PROMPTS,
  },
  {
    id: 'grief',
    name: 'Grief & loss',
    blurb: 'For carrying someone with you.',
    prompts: [
      'What do you miss most about them today?',
      'What would you tell them if they were here right now?',
      'What small thing reminded you of them recently?',
      'What are you carrying today that nobody can see?',
      'What did they teach you that you still use?',
      'What do you wish people understood about how you are doing?',
      'What felt heavier today than it looked from outside?',
      'What is something of theirs you are glad you kept?',
      'Where do you feel closest to them?',
      'What kindness helped you get through this week?',
      'What are you avoiding, and is that alright for now?',
      'What made you laugh today, and did it feel strange to?',
      'What would they be proud of you for, right now?',
      'What have you stopped explaining to people?',
      'What does a good day look like at the moment?',
      'What did you manage today, however small?',
      'What are you not ready to let go of yet?',
      'Who has stayed, and how?',
      'What has this taught you that you would rather not have learned?',
      'What do you want to remember exactly as it was?',
    ],
  },
  {
    id: 'gratitude',
    name: 'Gratitude',
    blurb: 'For noticing what is already here.',
    prompts: [
      'What went right today that you almost did not notice?',
      'Who made your day easier without being asked?',
      'What do you have now that you once hoped for?',
      'What ordinary thing would you miss if it vanished tomorrow?',
      'What did your body let you do today?',
      'What is working quietly in the background of your life?',
      'Who would you thank today if there were no awkwardness in it?',
      'What small comfort did you lean on?',
      'What went better than you feared?',
      'What did someone say to you that landed well?',
      'What part of your home are you glad of?',
      'What did you eat today that you enjoyed?',
      'What skill of yours made something easier today?',
      'What are you glad you said no to?',
      'What is beautiful about where you live?',
      'Who taught you something you still rely on?',
      'What has been given to you that you did not earn?',
      'What is easier now than it was a year ago?',
      'What sound today made you feel at home?',
      'What would past-you be delighted to know about today?',
    ],
  },
  {
    id: 'change',
    name: 'Change & transitions',
    blurb: 'For the in-between times.',
    prompts: [
      'What is ending, and how do you feel about it?',
      'What is beginning, ready or not?',
      'What did you leave behind that you do not miss?',
      'What do you miss that you did not expect to?',
      'Who are you becoming in this?',
      'What still feels unfamiliar?',
      'What has already started to feel normal?',
      'What would you tell someone about to go through this?',
      'What are you afraid this will cost you?',
      'What has surprised you about the change?',
      'What part of your old routine do you want to keep?',
      'What do you need before you will feel settled?',
      'What are you postponing until things calm down?',
      'Who has been steady through this?',
      'What version of yourself are you grieving?',
      'What have you outgrown without noticing?',
      'What is one thing that has not changed at all?',
      'What would settled actually look like?',
      'What have you learned that you could not have learned staying?',
      'What do you want to remember about this in-between time?',
    ],
  },
];

export function packById(id) {
  return PROMPT_PACKS.find((p) => p.id === id) || PROMPT_PACKS[0];
}
