// prompts.js — gentle, open, non-prescriptive reflection prompts. Shown in the
// "today's ritual" write card, one per day via a no-repeat deck (see deck.js).
export const PROMPTS = [
  "What's one small thing you're grateful for today?",
  'What moment from today would you like to remember?',
  "What's something that made you smile recently?",
  "What's weighing on your mind right now?",
  'What did you learn about yourself this week?',
  'What are you looking forward to?',
  "What's one kind thing you could do for yourself today?",
  'Who are you thankful for, and why?',
  "What's a small win you can celebrate?",
  'What would make today feel complete?',
  "What's something you'd like to let go of?",
  'When did you feel most at ease today?',
  "What's a challenge you're quietly proud of facing?",
  'What does rest look like for you right now?',
  "What's one thing you'd tell your past self?",
  "What's been giving you energy lately?",
  "What's been draining your energy lately?",
  'What did your body need today?',
  "What's a worry you can set down for now?",
  'What surprised you today?',
  'What are you curious about right now?',
  "What's something beautiful you noticed today?",
  'How did you show up for someone today?',
  'How did someone show up for you?',
  "What's a habit you'd like to nurture?",
  "What's one thing within your control today?",
  "What's a feeling you've been avoiding?",
  'What made today different from yesterday?',
  "What's a small comfort you're grateful for?",
  'What would you like more of in your days?',
  'What would you like less of in your days?',
  "What's a question you're sitting with?",
  'What did you do today that was just for you?',
  "What's something you're slowly getting better at?",
  "What's a boundary you're glad you kept?",
  'When did you feel most like yourself today?',
  "What's a memory that brought you peace lately?",
  "What's something you forgive yourself for?",
  "What are you holding onto that's no longer yours to carry?",
  "What's one hope you have for tomorrow?",
  'What sound, smell, or sight grounded you today?',
  "What's a strength you leaned on recently?",
  "What's something you'd like to say but haven't?",
  'How have you grown in the last year?',
  "What's a simple pleasure you enjoyed today?",
  "What's asking for your attention right now?",
  'What helped you get through a hard moment?',
  "What's a promise you'd like to make to yourself?",
  'What does "enough" feel like for you today?',
  "What's something you're proud of this week?",
  'Where did you find a little joy today?',
  "What's a thought you'd like to release before sleep?",
  "What's something you're learning to accept?",
  'Who or what made you feel supported lately?',
  "What's a small step you took toward something that matters?",
  "What's been on your heart today?",
  'What would you like to remember about this season of life?',
  "What's a fear that's softening over time?",
  'What gave today meaning, however small?',
  'What do you need to hear right now?',
];
